version: '3.9'

services:

  theia-base-38:
    image: registry.digitalocean.com/anubis/theia-base:python-3.8
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.8.12'
        BUILD_THEIA: 'ON'

  theia-base-39:
    image: registry.digitalocean.com/anubis/theia-base:python-3.9
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.9.10'
        BUILD_THEIA: 'ON'

  theia-base-310:
    image: registry.digitalocean.com/anubis/theia-base:python-3.10
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.10.2'
        BUILD_THEIA: 'ON'

  theia-base-38-bare:
    image: registry.digitalocean.com/anubis/theia-base:python-3.8-bare
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.8.12'
        BUILD_THEIA: 'OFF'

  theia-base-39-bare:
    image: registry.digitalocean.com/anubis/theia-base:python-3.9-bare
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.9.10'
        BUILD_THEIA: 'OFF'

  theia-base-310-bare:
    image: registry.digitalocean.com/anubis/theia-base:python-3.10-bare
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.10.2'
        BUILD_THEIA: 'OFF'

  webtop-base-ubuntu:
    image: registry.digitalocean.com/anubis/webtop-base:ubuntu
    build:
      context: ./webtop-base
      args: {}

  theia-golang:
    image: registry.digitalocean.com/anubis/theia-golang:latest
    build: ./theia-golang

  theia-xv6:
    image: registry.digitalocean.com/anubis/theia-xv6:latest
    build: ./theia-xv6

  theia-admin:
    image: registry.digitalocean.com/anubis/theia-admin:latest
    build: ./theia-admin

  theia-devops:
    image: registry.digitalocean.com/anubis/theia-devops:latest
    build: ./theia-devops

  theia-flask-39:
    image: registry.digitalocean.com/anubis/theia-flask:python-3.9
    build:
      context: ./theia-flask
      args:
        PY_VERSION: '3.9'

  theia-flask-310:
    image: registry.digitalocean.com/anubis/theia-flask:python-3.10
    build:
      context: ./theia-flask
      args:
        PY_VERSION: '3.10'

  theia-mysql-39:
    image: registry.digitalocean.com/anubis/theia-mysql:python-3.9
    build:
      context: ./theia-mysql
      args:
        PY_VERSION: '3.9'

  theia-mysql-310:
    image: registry.digitalocean.com/anubis/theia-mysql:python-3.10
    build:
      context: ./theia-mysql
      args:
        PY_VERSION: '3.10'

  theia-jepst:
    image: registry.digitalocean.com/anubis/theia-jepst:latest
    build: ./theia-jepst
